### ISSUE TITLE
cv2 error when running app.py

### ISSUE THREAD

**Issue by goldblum** [toxtli/anti-piracy-video-detection-neural-networks-string-algorithms#5]
Hi, I tried running this program and ran into the following error.  Any ideas what is happening?  Thanks!

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 10606
Traceback (most recent call last):
  File "app.py", line 692, in <module>
    get_and_compare_videos(sys.argv[4], sys.argv[5])
  File "app.py", line 470, in get_and_compare_videos
    compare_videos(video_path_1, video_path_2)
  File "app.py", line 119, in compare_videos
    objects_1 = detect_objects(frame_1, thresh, detection_graph, sess, category_index, sequence_sorted=sequence_sorted, sequence_type=sequence_type)
  File "app.py", line 507, in detect_objects
    image_np = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: /io/opencv/modules/imgproc/src/color.cpp:10606: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by goldblum** [comment]
Figured this out.  Nevermind.
